### ISSUE TITLE
"hardware info parse to json failed, error: %+vinvalid character '\\x01' looking for beginning of value" 

### ISSUE THREAD

**Issue by phoenixlhs** [swanchain/go-computing-provider#71]
Computing-Provider version:0.4.7
Node type:ECP
Description: When the ECP node is runnning,I found the ubi list have many fail jobs.Then I check the cp.log,found this message"time="2024-05-20 02:38:31.414" level=error msg="hardware info parse to json failed, error: %+vinvalid character '\\x01' looking for beginning of value" func=GetCpResource file="ubi.go:755"
![cplog](https://github.com/swanchain/go-computing-provider/assets/1990310/fdf79e57-e703-47bb-815b-170d42c5292d)
And the log of container resource-exporter shows "
{"gpu":{"driver_version":"","cuda_version":"","attached_gpus":0,"details":null},"machine_id":"d057a478-09c5-430f-9759-9c6b000fe56e","cpu_name":"AMD","cpu":{"total":"16","used":"10","free":"6"},"vcpu":{"total":"16","used":"10","free":"6"},"memory":{"total":"125 GiB","used":"12 GiB","free":"111 GiB"},"storage":{"total":"915 GiB","used":"707 GiB","free":"161 GiB"}}
The node not found nvm libnvidia, if the node does not have a GPU, this error can be ignored.
{"gpu":{"driver_version":"","cuda_version":"","attached_gpus":0,"details":null},"machine_id":"d057a478-09c5-430f-9759-9c6b000fe56e","cpu_name":"AMD","cpu":{"total":"16","used":"10","free":"6"},"vcpu":{"total":"16","used":"10","free":"6"},"memory":{"total":"125 GiB","used":"12 GiB","free":"111 GiB"},"storage":{"total":"915 GiB","used":"707 GiB","free":"161 GiB"}}
The node not found nvm libnvidia, if the node does not have a GPU, this error can be ignored.
![resource-exporter](https://github.com/swanchain/go-computing-provider/assets/1990310/b3e5e607-7f46-4688-b7d1-c9f1f795b3f2)

**Comment by Normalnoise** [comment]
we have fixed the bug, please use this branch to rebuild the binary
https://github.com/swanchain/go-computing-provider/tree/releases

**Comment by phoenixlhs** [comment]
Already update to 0.4.8,but this error still comes out.
Here is the cp.log.I have two servers,they both have the same problem.
[cp.log](https://github.com/swanchain/go-computing-provider/files/15482732/cp.log)

**Comment by sonic-chain** [comment]
After this error occurs, cp will automatically restart the `resource-exporter` component to work normally.

**Comment by Normalnoise** [comment]
Please upgrade to v0.5.1
