### ISSUE TITLE
computing-provider  Fails TLS Certificate Verification in Container

### ISSUE THREAD

**Issue by xiaotanttt** [swanchain/go-computing-provider#79]
Problem Description:
While running computing-provider version 0.4.8 within a container and executing tasks, an error occurred where TLS certificate verification failed, preventing the retrieval of Filecoin proof parameters.

Key Error Message:
tls: failed to verify certificate: x509: certificate signed by unknown authority

Additional Notes:
The error occurred during the task execution process within the container.
The 512M proof parameter data has been pre-downloaded to the local environment.
The environment variable PARENT_PATH is defined.

**Comment by yejiayu** [comment]
Try adding this code to your dockerfile
```dockerfile
RUN apt-get update && \
    apt-get install -y ca-certificates
```

**Comment by xiaotanttt** [comment]
> Try adding this code to your dockerfile
> 
> ```dockerfile
> RUN apt-get update && \
>     apt-get install -y ca-certificates
> ```

I tried doing it this way, but it's still the same result. I'm out of options.

**Comment by Normalnoise** [comment]
please check your cp log and $CP_PATH/ubi.log
@xiaotanttt

**Comment by xiaotanttt** [comment]
> please check your cp log and $CP_PATH/ubi.log @xiaotanttt

`2024-05-27T08:52:35.172685137Z 2024-05-27T08:52:35.172Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e>2024-05-27T08:52:35.172710883Z 2024-05-27T08:52:35.172Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmZCvxKcKP97vDAk8Nxs9R1fWtqpjQrAhhfXPoCi1nkDoF
2024-05-27T08:52:35.727788150Z 2024-05-27T08:52:35.727Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-5294475db5237a2e83c3e52fd6c2b03859a1831d45>2024-05-27T08:52:35.727804800Z 2024-05-27T08:52:35.727Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmUiVYCQUgr6Y13pZFr8acWpSM4xvTXUdcvGmxyuHbKhsc
2024-05-27T08:52:36.254488854Z 2024-05-27T08:52:36.254Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c>2024-05-27T08:52:36.254510741Z 2024-05-27T08:52:36.254Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmSTCXF2ipGA3f6muVo6kHc2URSx6PzZxGUqu7uykaH5KU
2024-05-27T08:52:36.789045583Z 2024-05-27T08:52:36.788Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-fb9e095bebdd77511c0269b967b4d87ba8b8a525edaa0e165d>2024-05-27T08:52:36.789080499Z 2024-05-27T08:52:36.788Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmaQsTLL3nc5dw6wAvaioJSBfd1jhQrA2o6ucFf7XeV74P
2024-05-27T08:52:37.332584242Z 2024-05-27T08:52:37.332Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-2-102e1444a7e9a97ebf1e3d6855dcc77e66c011ea66f936d9b2>2024-05-27T08:52:37.332605869Z 2024-05-27T08:52:37.332Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/Qmd794Jty7k26XJ8Eg4NDEks65Qk8G4GVfGkwqvymv8HAg
2024-05-27T08:52:37.868175044Z 2024-05-27T08:52:37.867Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-2-sha256_hasher-96f1b4a04c5c51e4759bbf224bb>2024-05-27T08:52:37.868206048Z 2024-05-27T08:52:37.868Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmehSmC6BhrgRZakPDta2ewoH9nosNzdjCqQRXsNFNUkLN
2024-05-27T08:52:38.396309431Z 2024-05-27T08:52:38.395Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b>2024-05-27T08:52:38.396344633Z 2024-05-27T08:52:38.396Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmbfQjPD7EpzjhWGmvWAsyN2mAZ4PcYhsf3ujuhU9CSuBm
2024-05-27T08:52:38.937255029Z 2024-05-27T08:52:38.936Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-92180959e1918d26350b8e6cfe217bbdd0a2d8de51ebec2690>2024-05-27T08:52:38.937287820Z 2024-05-27T08:52:38.937Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmdcpKUQvHM8RFRVKbk1yHfEqMcBzhtFWKRp9SNEmWq37i
2024-05-27T08:52:39.488742753Z 2024-05-27T08:52:39.488Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-61fa69f38b9cc771ba27b670124714b4ea77fbeae05e377fb8>2024-05-27T08:52:39.488773207Z 2024-05-27T08:52:39.488Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/Qma5WL6abSqYg9uUQAZ3EHS286bsNsha7oAGsJBD48Bq2q
2024-05-27T08:52:40.014647876Z 2024-05-27T08:52:40.014Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d5>2024-05-27T08:52:40.014692503Z 2024-05-27T08:52:40.014Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmbmUMa3TbbW3X5kFhExs6WgC4KeWT18YivaVmXDkB6ANG
2024-05-27T08:52:40.532120159Z 2024-05-27T08:52:40.531Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4f>2024-05-27T08:52:40.532150149Z 2024-05-27T08:52:40.531Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmfCeddjFpWtavzfEzZpJfzSajGNwfL4RjFXWAvA9TSnTV
2024-05-27T08:52:41.066777417Z 2024-05-27T08:52:41.066Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-fil-inner-product-v1.srs from https://proofs.filecoin.io/ipfs/
2024-05-27T08:52:41.066797721Z 2024-05-27T08:52:41.066Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/Qmdq44DjcQnFfU3PJcdX7J49GCqcUYszr1TxMbHtAkvQ3g
2024-05-27T08:52:41.592671665Z 2024-05-27T08:52:41.591Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b6>2024-05-27T08:52:41.592752090Z 2024-05-27T08:52:41.592Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmfA31fbCWojSmhSGvvfxmxaYCpMoXP95zEQ9sLvBGHNaN
2024-05-27T08:52:42.114306081Z 2024-05-27T08:52:42.114Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c>2024-05-27T08:52:42.114334721Z 2024-05-27T08:52:42.114Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmR9i9KL3vhhAqTBGj1bPPC7LvkptxrH9RvxJxLN1vvsBE
2024-05-27T08:52:42.651287931Z 2024-05-27T08:52:42.651Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:244  Fetching /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-61fa69f38b9cc771ba27b670124714b4ea77fbeae05e377fb8>2024-05-27T08:52:42.651318562Z 2024-05-27T08:52:42.651Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:262  GET https://proofs.filecoin.io/ipfs/QmUa7f9JtJMsqJJ3s3ZXk6WyF4xJLE8FiqYskZGgk8GCDv
2024-05-27T08:52:43.179782268Z 2024-05-27T08:52:43.179Z ^[[34mINFO^[[0m paramfetch      go-paramfetch@v0.0.4/paramfetch.go:233  parameter and key-fetching complete
2024-05-27T08:52:43.180603502Z 2024-05-27T08:52:43.179Z ^[[33mWARN^[[0m ubi-bench       ubi-bench/main.go:113   getting params:
2024-05-27T08:52:43.180932236Z     main.glob..func4
2024-05-27T08:52:43.180944607Z         /opt/ubi-benchmark/cmd/ubi-bench/main.go:585
2024-05-27T08:52:43.180951807Z   - the following errors occurred:
2024-05-27T08:52:43.180957679Z      -  fetching file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk failed:
2024-05-27T08:52:43.180965439Z             github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
2024-05-27T08:52:43.180971418Z                 /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.4/paramfetch.go:142
2024-05-27T08:52:43.180977381Z           - Get "https://proofs.filecoin.io/ipfs/Qmf93EMrADXAK6CyiSfE8xx45fkMfR3uzKEPCvZC1n2kzb": tls: failed to verify certificate: x509: certificate signed by unknown authority
2024-05-27T08:52:43.180984423Z      -  fetching file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk failed:
2024-05-27T08:52:43.180990876Z             github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
2024-05-27T08:52:43.180996628Z                 /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.4/paramfetch.go:142
2024-05-27T08:52:43.181002430Z           - Get "https://proofs.filecoin.io/ipfs/QmWV8rqZLxs1oQN9jxNWmnT1YdgLwCcscv94VARrhHf1T7": tls: failed to verify certificate: x509: certificate signed by unknown authority
2024-05-27T08:52:43.181009276Z      -  fetching file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-ecd683648512ab1765faa2a5f14bab48f676e633467f0aa8aad4b55dcb0652bb.vk failed:
2024-05-27T08:52:43.181016105Z             github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
2024-05-27T08:52:43.181021947Z                 /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.4/paramfetch.go:142
2024-05-27T08:52:43.181027649Z           - Get "https://proofs.filecoin.io/ipfs/QmYCuipFyvVW1GojdMrjK1JnMobXtT4zRCZs1CGxjizs99": tls: failed to verify certificate: x509: certificate signed by unknown authority`

After I opened it, this kind of log was displayed.

**Comment by snakeeeeeeeee** [comment]
I am also troubled by this problem, how to solve it?

**Comment by snakeeeeeeeee** [comment]
> > I am also troubled by this problem, how to solve it?
> 
> I am at a loss for this, and can only shut down my node first.
I tried changing vps and the problem was solved. I guess this might have something to do with the environment of the machine the node is running on?
Duplicate of #

**Comment by snakeeeeeeeee** [comment]
I tried changing vps and the problem was solved. I guess this might have something to do with the environment of the machine the node is running on?

> > 我也被这个问题困扰，如何解决？
> 
> 我对此束手无策，只能先关闭我的节点。

I tried changing vps and the problem was solved. I guess this might have something to do with the environment of the machine the node is running on?

**Comment by snakeeeeeeeee** [comment]
> > I am also troubled by this problem, how to solve it?
> 
> I am at a loss for this, and can only shut down my node first.

I tried changing vps and the problem was solved. I guess this might have something to do with the environment of the machine the node is running on?

**Comment by xiaotanttt** [comment]
> > > I am also troubled by this problem, how to solve it?
> > 
> > 
> > I am at a loss for this, and can only shut down my node first.
> 
> I tried changing vps and the problem was solved. I guess this might have something to do with the environment of the machine the node is running on?

This VPS is newly activated, and I have also tried using other devices, but the issue still occurs with a certain probability.

**Comment by xiaotanttt** [comment]
The issue persists even after updating to version 0.5.1, and the relevant data has been verified to show that the download is complete.
![微信图片_20240618224623](https://github.com/swanchain/go-computing-provider/assets/129300486/d5494f65-67c9-4abe-8886-55f3ab9528bb)
![微信图片_20240618233723](https://github.com/swanchain/go-computing-provider/assets/129300486/f3ce9a1c-a1f3-4c89-8b6f-7cc5aa52a716)
![微信图片_20240618233735](https://github.com/swanchain/go-computing-provider/assets/129300486/871545d6-52da-4608-80d4-9529f3aafcd7)

**Comment by Normalnoise** [comment]
please ensure your CP following the right cmd:
`FIL_PROOFS_PARAMETER_CACHE` is required. please it has been set your V28 params path, you can change`$PARENT_PATH` to your local path 
```
#!/bin/bash
export FIL_PROOFS_PARAMETER_CACHE=$PARENT_PATH
export RUST_GPU_TOOLS_CUSTOM_GPU="GeForce RTX 4090:16384"   
        
nohup ./computing-provider ubi daemon >> cp.log 2>&1 &
```
